package vu.lt.mybatis.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.NAME
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    private Integer showId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.EPISODECOUNT
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    private Integer episodecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.ID
     *
     * @return the value of PUBLIC.ROLE.ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.ID
     *
     * @param id the value for PUBLIC.ROLE.ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.NAME
     *
     * @return the value of PUBLIC.ROLE.NAME
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.NAME
     *
     * @param name the value for PUBLIC.ROLE.NAME
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.SHOW_ID
     *
     * @return the value of PUBLIC.ROLE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public Integer getShowId() {
        return showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.SHOW_ID
     *
     * @param showId the value for PUBLIC.ROLE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public void setShowId(Integer showId) {
        this.showId = showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.EPISODECOUNT
     *
     * @return the value of PUBLIC.ROLE.EPISODECOUNT
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public Integer getEpisodecount() {
        return episodecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.EPISODECOUNT
     *
     * @param episodecount the value for PUBLIC.ROLE.EPISODECOUNT
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    public void setEpisodecount(Integer episodecount) {
        this.episodecount = episodecount;
    }
}