package vu.lt.mybatis.model;

public class ShowGenre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOW_GENRE.GENRE_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    private Integer genreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOW_GENRE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    private Integer showId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOW_GENRE.GENRE_ID
     *
     * @return the value of PUBLIC.SHOW_GENRE.GENRE_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    public Integer getGenreId() {
        return genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOW_GENRE.GENRE_ID
     *
     * @param genreId the value for PUBLIC.SHOW_GENRE.GENRE_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOW_GENRE.SHOW_ID
     *
     * @return the value of PUBLIC.SHOW_GENRE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    public Integer getShowId() {
        return showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOW_GENRE.SHOW_ID
     *
     * @param showId the value for PUBLIC.SHOW_GENRE.SHOW_ID
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    public void setShowId(Integer showId) {
        this.showId = showId;
    }
}