package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Genre;

@Mapper
public interface GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int insert(Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    Genre selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    List<Genre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int updateByPrimaryKey(Genre record);
}