package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Role;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int updateByPrimaryKey(Role record);
}