package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Role;
import vu.lt.mybatis.model.Show;

@Mapper
public interface ShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int insert(Show record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    Show selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    List<Show> selectAll();

    List<Role> selectAllRoles(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW
     *
     * @mbg.generated Tue Apr 27 12:15:51 EEST 2021
     */
    int updateByPrimaryKey(Show record);
}