package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.ShowGenre;

@Mapper
public interface ShowGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW_GENRE
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    int insert(ShowGenre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOW_GENRE
     *
     * @mbg.generated Tue Apr 27 12:28:50 EEST 2021
     */
    List<ShowGenre> selectAll();
}